// <auto-generated />
using System;
using DDDRedeSocialUniversitaria.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DDDRedeSocialUniversitaria.Infra.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20250326002510_Intial")]
    partial class Intial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DDDRedeSocialUniversitaria.Domain.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExigeInscricao")
                        .HasColumnType("bit");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("DDDRedeSocialUniversitaria.Domain.Postagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Comentarios")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Postagens");
                });

            modelBuilder.Entity("DDDRedeSocialUniversitaria.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EventoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostagemId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("PostagemId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("DDDRedeSocialUniversitaria.Domain.Postagem", b =>
                {
                    b.HasOne("DDDRedeSocialUniversitaria.Domain.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("DDDRedeSocialUniversitaria.Domain.Usuario", b =>
                {
                    b.HasOne("DDDRedeSocialUniversitaria.Domain.Evento", null)
                        .WithMany("Inscritos")
                        .HasForeignKey("EventoId");

                    b.HasOne("DDDRedeSocialUniversitaria.Domain.Postagem", null)
                        .WithMany("Curtidas")
                        .HasForeignKey("PostagemId");

                    b.HasOne("DDDRedeSocialUniversitaria.Domain.Usuario", null)
                        .WithMany("Seguidores")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("DDDRedeSocialUniversitaria.Domain.Evento", b =>
                {
                    b.Navigation("Inscritos");
                });

            modelBuilder.Entity("DDDRedeSocialUniversitaria.Domain.Postagem", b =>
                {
                    b.Navigation("Curtidas");
                });

            modelBuilder.Entity("DDDRedeSocialUniversitaria.Domain.Usuario", b =>
                {
                    b.Navigation("Seguidores");
                });
#pragma warning restore 612, 618
        }
    }
}
